(Re-)create Flux Helm secrets prior to (re-)creating Flux
Otherwise, upon a re-installation, Flux will start with old certs,
and `eksctl` then times out:

```console
[ℹ]  Waiting for Helm Operator to start
[...]
ERROR: logging before flag.Parse: E0829 17:28:35.778721   88133 portforward.go:331] an error occurred forwarding 49582 -> 3030: error forwarding port 3030 to pod 8e705fc70fe04bb25ec354655785ef71fa025e345e091c5349a56fc8309ed4a2, uid : exit status 1: 2019/08/29 08:28:35 socat[18057] E connect(5, AF=2 127.0.0.1:3030, 16): Connection refused
[!]  Helm Operator is not ready yet (Get http://127.0.0.1:49582/healthz: EOF), retrying ...
[...]
[✖]  timed out waiting for Helm Operator to be operative
```

```console
$ kubectl -n flux logs --follow flux-helm-operator-6bc7c85bb5-qsvqp
caller=helm.go:84 component=helm warning="unable to connect to Tiller"
err="error getting tiller version: context deadline exceeded"
host=tiller-deploy.flux:44134 options="{
  Host: Port: Namespace:flux TLSVerify:true TLSEnable:true
  TLSKey:/etc/fluxd/helm/tls.key TLSCert:/etc/fluxd/helm/tls.crt
  TLSCACert:/etc/fluxd/helm-ca/ca.crt TLSHostname:
}"
```

Note that the namespace is passed as it may be required before
creating the secrets, otherwise, `eksctl` would fail with:
```
[✖]  namespaces "flux" not found
```