Fix typo in userdocs additionalEndpointServices Example
Before this patch, copying the example resulted in the following eksctl error:
    Error: invalid value in privateCluster.additionalEndpointServices: unsupported endpoint service "log"

This patch fixes the example to correctly use "logs" instead of "log".