fix(doc): `brew tap weaveworks/tap`
Is required before installing `eksctl` with Homebrew. Otherwise `brew install` fails like:

```console
Error: No available formula with the name "weaveworks/tap/eksctl"
Please tap it and then try again: brew tap weaveworks/tap
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
```